BLOCKING_ATTRIBUTE: 3
COMPARISON_ATTRIBUTE: [1,2,3,4]
TOTAL_RATE: 8/100
THRESHOLD: 1

input_files:
  input_file_1: "../data/pse_dec.1.1"
  input_file_2: "../data/pse_dec.1.2"

header: ['simulant_id', 'first_name', 'middle_initial', 'last_name', 'age',     
       'date_of_birth', 'street_number', 'street_name', 'unit_number', 'city',
       'state', 'zipcode', 'relation_to_reference_person', 'sex',
       'race_ethnicity']

id_column: "simulant_id"

sample_output:
  output_file_1: "../data/out.1"
  output_file_2: "../data/out.2"

rla_xml_file: "../data/config.xml"


run:
  attribute_selection: True
  RLA_CL_EXTRACT: True
  feature_selection: True
  apiori: True

sample_size: 50000