# Attribute Selection
BLOCKING_ATTRIBUTE: 1
COMPARISON_ATTRIBUTE: [1,2,3,4]
TOTAL_RATE: 0.02
THRESHOLD: 1

input_files:
  input_file_1: "../data/pse_dec.1.1"
  input_file_2: "../data/pse_dec.1.2"

header: ['simulant_id', 'first_name', 'middle_initial', 'last_name', 'age',     
       'date_of_birth', 'street_number', 'street_name', 'unit_number', 'city',
       'state', 'zipcode', 'relation_to_reference_person', 'sex',
       'race_ethnicity']

id_column: "simulant_id"

sample_output:
  output_file_1: '../data/out.1.1'
  output_file_2: '../data/out.1.2'

# RLA_CL_EXTRACT
rla_xml_file: "../data/config_test.xml"

# Feature Pruning
FEATURE_PRUNE_KEEP: 0.2
pruned_output: "../data/pruned_out.csv"

# Apriori
rules_output: "../data/rules_out.csv"



# RUN
run:
  attribute_selection: False
  RLA_CL_EXTRACT: True
  feature_prune: True
  apriori: True

sample_size: 50000